AWSTemplateFormatVersion: "2010-09-09"

Description: Create a public and private EC2 instance
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: nhom1keypair
  PublicSubnetId:
    Type: String
  PublicInstanceSecurityGroupId:
    Type: String
  PrivateSubnetId:
    Type: String
  PrivateInstanceSecurityGroupId:
    Type: String  

Resources:
  PublicInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-007868005aea67c54 # Replace with a valid AMI ID
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: !Ref PublicSubnetId
          GroupSet:
            - !Ref PublicInstanceSecurityGroupId

  PrivateInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-014d544cfef21b42d # Replace with a valid AMI ID
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: !Ref PrivateSubnetId
          GroupSet:
            - !Ref PrivateInstanceSecurityGroupId

Outputs:
  PublicInstanceId:
    Description: Id of public instance 
    Value: !Ref PublicInstance
    Export:
      Name: PublicInstanceId

  PrivateInstanceId:
    Description: Id of private instance 
    Value: !Ref PrivateInstance
    Export:
      Name: PrivateInstanceId