AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a NAT Gateway

Parameters:
  PublicSubnetId:
    Type: String

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref PublicSubnetId

Outputs:
  NATGatewayId:
    Description: Id of NAT Gateway
    Value: !Ref NATGateway
    Export:
      Name: NATGatewayId