project:
  name: cloudformation-template-tests
  regions:
    - us-east-1

tests:
  vpc-test:
    template: modules/vpc.yaml
  subnet-test:
    template: modules/subnets.yaml
    parameters:
      VPCId: !GetAtt vpc-test.VPCId
  securitygroup-test:
    template: modules/security_groups.yaml
    parameters:
      VPCId: !GetAtt vpc-test.VPCId
  natgateway-test:
    template: modules/natgateways.yaml
    parameters:
      PublicSubnetId: !GetAtt subnet-test.PublicSubnetId
  routetable-test:
    template: modules/route_tables.yaml
    parameters:
      VPCId: !GetAtt vpc-test.VPCId
      PublicSubnetId: !GetAtt subnet-test.PublicSubnetId
      PrivateSubnetId: !GetAtt subnet-test.PrivateSubnetId
      NATGatewayId: !GetAtt natgateway-test.NATGatewayId
  ec2-test:
    template: modules/ec2_instances.yaml
    parameters:
      PublicSubnetId: !GetAtt subnet-test.PublicSubnetId
      PrivateSubnetId: !GetAtt subnet-test.PrivateSubnetId
      PublicInstanceSecurityGroupId: !GetAtt securitygroup-test.PublicInstanceSecurityGroupId
      PrivateInstanceSecurityGroupId: !GetAtt securitygroup-test.PrivateInstanceSecurityGroupId
