version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint taskcat  # Cài đặt cfn-lint và Taskcat
  pre_build:
    commands:
      - echo "Running cfn-lint to validate templates..."
      - |
        for template in $(find templates/ -name '*.yaml' -or -name '*.yml'); do
          echo "Linting $template"
          cfn-lint $template  # Kiểm tra từng file CloudFormation
        done
  build:
    commands:
      - echo "Running Taskcat to test CloudFormation templates..."
      - taskcat test run  # Chạy Taskcat kiểm tra toàn bộ template
  post_build:
    commands:
      - echo "Build process completed."
artifacts:
  files:
    - "**/*"
  discard-paths: no
